version: '3.4'

services:
  crud-backend:
    container_name: crud-backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '9000:9000'
    networks:
      - crud-network
    volumes:
      - ./:/var/www/crud-backend
    environment:
      # cs fixer not working on 8.2 yet
      PHP_CS_FIXER_IGNORE_ENV: 1

  crud-database:
    image: postgres:latest
    container_name: crud-database
    environment:
      POSTGRES_DB: 'crud'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'zadanieTestoweRankomat'
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - crud-network
    volumes:
      - database:/var/lib/postgresql/data
    tty: true

  crud-nginx:
    container_name: crud-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - crud-network
    restart: unless-stopped
    volumes:
      - ./:/var/www/crud-backend
    depends_on:
      - crud-backend
      - crud-database

  crud-frontend:
    container_name: crud-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: npm run start
    networks:
      - crud-network





volumes:
  database:

networks:
  crud-network:
